### ISSUE TITLE
Remove the bars of orphan tags

### ISSUE THREAD

**Issue by kvnol** [Netflix/netflix.github.com#111]
On HTML5, the bars on orphan tags is not necessary.

**Comment by laumair** [comment]
@kvnol Can you add a description for this please?

**Comment by speedywarp** [comment]
is the issue resolved?

**Comment by lesha0** [comment]
Hey @kvnol,

To do this, you can simply use the tag without closing it. For example, instead of `<br/>`, you can use just `<br>` in HTML5.
