### ISSUE TITLE
List view: show project logos

### ISSUE THREAD

**Issue by hastebrot** [Netflix/netflix.github.com#86]
I'd like to see the project logos in list view. The logo image would fit nicely on the left side of each list view item.

Thumbnail view:

![netflix-thumb-view](https://cloud.githubusercontent.com/assets/496255/7007080/af578f0c-dc86-11e4-9cde-ab25916bae0d.png)

List view:

![netflix-list-view](https://cloud.githubusercontent.com/assets/496255/7007105/e1989f2e-dc86-11e4-92c5-70b544503d0f.png)

**Comment by iherndon** [comment]
I would like to take this on. I have already forked the  repo.

**Comment by aspyker** [comment]
we have re-designed the website in a way that makes this issue no longer valid.  thanks for the thoughts.
