### ISSUE TITLE
Design Update

### ISSUE THREAD

**Issue by zethussuen** [Netflix/netflix.github.com#89]
Anyone ever take a stab at a UI refresh for our OSS page?

Experimenting with list views and card views for the repositories

![netflix oss](https://cloud.githubusercontent.com/assets/754158/7954956/1ae7b1e6-0989-11e5-94b3-8031e6f5a45a.png)

**Comment by aspyker** [comment]
This was opened before the new netflix.github.io re-design.  Thanks for the thoughts here.  If you have additional thoughts based on the new website design, let us know.
